const cities={
  prague:{name:"PRAGUE",kr:"프라하",country:"CZECHIA · CENTRAL EUROPE",score:94,season:"APR — OCT",cost:168,pos:"left top",note:"붉은 지붕과 고딕 첨탑, 강 위로 번지는 저녁빛. 오래된 골목을 걷고 싶은 당신에게 꼭 맞는 도시예요.",tags:["#예술과건축","#오래된골목","#강변산책"],days:[["도착, 첫 번째 골목","구시가지 광장과 천문시계 사이를 천천히 걷는 날"],["다리 위의 아침","사람이 적은 새벽 카를교와 강변 카페"],["성 안의 오후","프라하성, 황금소로, 오래된 정원의 빛"],["현지인의 식탁","홀레쇼비체 마켓과 작은 비스트로 탐방"],["음악이 흐르는 밤","재즈 클럽과 블타바강 야경 크루즈"],["마지막 엽서","좋았던 골목을 다시 걷고 작은 기념품 고르기"]]},
  budapest:{name:"BUDAPEST",kr:"부다페스트",country:"HUNGARY · DANUBE RIVER",score:91,season:"MAR — NOV",cost:158,pos:"center top",note:"도나우강을 사이에 둔 두 도시와 오래된 온천. 낮과 밤의 표정이 완전히 다른 로맨틱한 여행지예요.",tags:["#도시의밤","#온천휴식","#강변풍경"],days:[["부다와 페스트","세체니 다리를 건너 두 도시의 첫인상 만나기"],["왕궁의 언덕","어부의 요새와 오래된 트램이 있는 오후"],["온천의 시간","세체니 온천에서 여행의 속도를 낮추기"],["중앙시장 미식","굴라시와 파프리카, 로컬 디저트 탐방"],["도나우의 밤","국회의사당이 빛나는 강변 야경 산책"],["카페의 도시","뉴욕 카페와 작은 서점에서 보내는 마지막 날"]]},
  vienna:{name:"VIENNA",kr:"빈",country:"AUSTRIA · IMPERIAL CITY",score:88,season:"APR — DEC",cost:196,pos:"right top",note:"클래식 음악과 미술관, 우아한 카페 문화가 하루를 채우는 도시. 예술을 오래 바라보는 여행에 어울려요.",tags:["#클래식예술","#카페문화","#정원산책"],days:[["링슈트라세","트램을 타고 만나는 빈의 고전 건축"],["클림트의 황금빛","벨베데레 궁전과 미술관에서 보내는 오후"],["카페의 시간","멜랑주와 자허토르테를 즐기는 느린 하루"],["쇤브룬 정원","궁전과 언덕을 잇는 긴 산책"],["음악이 있는 밤","작은 콘서트홀에서 만나는 클래식 공연"],["나슈마르크트","시장과 디자인 숍을 둘러보는 마지막 장면"]]},
  porto:{name:"PORTO",kr:"포르투",country:"PORTUGAL · DOURO RIVER",score:85,season:"MAY — OCT",cost:214,pos:"left bottom",note:"푸른 타일과 노을빛 강변, 언덕을 오르는 노란 트램. 바다와 오래된 도시를 함께 원하는 여행자에게 좋아요.",tags:["#푸른타일","#강변노을","#골목사진"],days:[["히베이라의 첫빛","도루강과 알록달록한 집들이 맞이하는 오후"],["아줄레주 산책","상벤투역과 오래된 교회의 푸른 타일"],["와인의 강","가이아 지구 와이너리와 석양 크루즈"],["시장과 식탁","볼량시장과 프란세지냐 맛보기"],["대서양 끝에서","포스 해변을 따라 걷는 긴 산책"],["트램과 서점","렐루서점과 빈티지 트램으로 마무리"]]}
};
const keywordButtons=[...document.querySelectorAll(".keyword")],durationButtons=[...document.querySelectorAll("[data-days]")],cityTabs=[...document.querySelectorAll(".city-tab")];
const budget=document.querySelector("#budget"),budgetOutput=document.querySelector("#budgetOutput"),durationOutput=document.querySelector("#durationOutput");let selectedDays=6,currentCity="prague";
function selectedKeywords(){return keywordButtons.filter(b=>b.classList.contains("active")).map(b=>b.querySelector("strong").textContent)}
function updateBudget(){const value=Number(budget.value);budgetOutput.value=`${value}만원`;budget.style.setProperty("--progress",`${((value-80)/420)*100}%`);document.querySelector("#factBudget").textContent=`약 ${Math.min(value,cities[currentCity].cost+Math.max(0,selectedDays-6)*18)}만원`}
keywordButtons.forEach(button=>button.addEventListener("click",()=>{const active=selectedKeywords().length;if(!button.classList.contains("active")&&active>=3){showToast("키워드는 세 개까지 선택할 수 있어요.");return}button.classList.toggle("active");if(selectedKeywords().length===0)button.classList.add("active")}));
budget.addEventListener("input",updateBudget);
durationButtons.forEach(button=>button.addEventListener("click",()=>{durationButtons.forEach(b=>b.classList.remove("active"));button.classList.add("active");selectedDays=Number(button.dataset.days);const label=selectedDays>=11?"10일 이상":`${selectedDays-1}박 ${selectedDays}일`;durationOutput.value=label;document.querySelector("#factDays").textContent=label;renderDays();updateBudget()}));
function setCity(key){currentCity=key;const city=cities[key],card=document.querySelector("#destinationCard");card.classList.add("changing");setTimeout(()=>{document.querySelector("#destinationName").textContent=city.name;document.querySelector("#destinationKr").textContent=city.kr;document.querySelector("#destinationCountry").textContent=city.country;document.querySelector("#destinationNote").textContent=city.note;document.querySelector("#factSeason").textContent=city.season;document.querySelector("#matchScore").textContent=city.score;document.querySelector("#storyCity").textContent=city.kr;document.querySelector("#destinationArt").style.backgroundPosition=city.pos;document.querySelector("#tagRow").innerHTML=city.tags.map(tag=>`<span>${tag}</span>`).join("");cityTabs.forEach(tab=>tab.classList.toggle("active",tab.dataset.city===key));renderDays();updateBudget();card.classList.remove("changing")},220)}
cityTabs.forEach(tab=>tab.addEventListener("click",()=>setCity(tab.dataset.city)));
function renderDays(){const city=cities[currentCity],count=Math.min(selectedDays,city.days.length),rail=document.querySelector("#dayRail"),panels=document.querySelector("#dayPanels");rail.innerHTML="";panels.innerHTML="";for(let i=0;i<count;i++){const railButton=document.createElement("button");railButton.textContent=`DAY ${String(i+1).padStart(2,"0")}`;if(i===0)railButton.classList.add("active");railButton.addEventListener("click",()=>{document.querySelectorAll(".day-rail button").forEach(b=>b.classList.remove("active"));railButton.classList.add("active");panels.children[i].scrollIntoView({behavior:"smooth",block:"center"})});rail.appendChild(railButton);const panel=document.createElement("article");panel.className="day-panel";panel.innerHTML=`<div class="day-thumb" style="--pos:${["left top","center top","right top","left bottom","center bottom","right bottom"][i]}"></div><div class="day-copy"><small>DAY ${String(i+1).padStart(2,"0")} · CURATED ROUTE</small><h3>${city.days[i][0]}</h3><p>${city.days[i][1]}</p></div><span class="day-toggle">+</span><div class="day-detail">오전과 오후 동선 사이에 충분한 여백을 두었어요. 장소를 저장하면 식당과 교통 정보까지 이어서 확인할 수 있습니다.</div>`;panel.addEventListener("click",()=>panel.classList.toggle("expanded"));panels.appendChild(panel)}}
document.querySelector("#generateButton").addEventListener("click",event=>{const button=event.currentTarget;button.classList.add("loading");button.querySelector("strong").textContent="취향을 읽는 중...";const keys=keywordButtons.filter(b=>b.classList.contains("active")).map(b=>b.dataset.key);let city="prague";if(keys.includes("night"))city="budapest";else if(keys.includes("food")&&Number(budget.value)>210)city="porto";else if(keys.includes("art")&&!keys.includes("water"))city="vienna";setTimeout(()=>{setCity(city);button.classList.remove("loading");button.querySelector("strong").textContent="나의 여행 그리기";document.querySelector("#routes").scrollIntoView({behavior:"smooth"});showToast("당신의 취향에 맞는 도시를 찾았어요.")},900)});
document.querySelectorAll("[data-scroll]").forEach(button=>button.addEventListener("click",()=>document.querySelector(`#${button.dataset.scroll}`).scrollIntoView({behavior:"smooth"})));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")}),{threshold:.13});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
window.addEventListener("scroll",()=>document.querySelector("#topbar").classList.toggle("sticky",scrollY>90));
const hero=document.querySelector(".hero"),watercolor=document.querySelector(".watercolor-layer");hero.addEventListener("pointermove",event=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const x=(event.clientX/innerWidth-.5)*10,y=(event.clientY/innerHeight-.5)*7;watercolor.style.transform=`scale(1.04) translate(${x}px,${y}px)`});hero.addEventListener("pointerleave",()=>watercolor.style.transform="scale(1.04)");
let toastTimer;function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2200)}
renderDays();updateBudget();
